#define B7_AUDIO  // B7 (timer 1) exposed on Elite-C
#define NO_MUSIC_MODE

// SEEGSON Rewire System Boot
#define SEEGSON QD_NOTE(_C4), QD_NOTE(_REST), QD_NOTE(_E4), QD_NOTE(_REST), QD_NOTE(_G4), QD_NOTE(_REST), QD_NOTE(_C4), QD_NOTE(_REST), QD_NOTE(_E4), QD_NOTE(_REST), QD_NOTE(_G4), QD_NOTE(_REST), QD_NOTE(_C5),
#define STARTUP_SONG SONG(SEEGSON)

#undef AUDIO_ON_SOUND
#define AUDIO_ON_SOUND E__NOTE(_C4), E__NOTE(_C5),
#undef AUDIO_OFF_SOUND
#define AUDIO_OFF_SOUND E__NOTE(_C5), E__NOTE(_C4),

#define AUDIO_CLICKY
#define AUDIO_CLICKY_FREQ_DEFAULT 70.0f
